spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:mariadb://localhost:3306/test
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        open-in-view: false
server:
    port: 8030
    servlet:
        encoding:
            charset: UTF-8
    tomcat:
        uri-encoding: UTF-8
logging:
    level:
        root: info
        boot:
            exam:
                demo: DEBUG