spring:
    profiles:
        active:
            - local
        group:
            local:
                - db-local
                - local
            dev:
                - db-dev
                - dev
            prod:
                - db-prod
                - prod
        include:
                - db
                - my-service
                - site
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    output:
        ansi:
            enabled: always
logging:
    config: classpath:log4j2.yml